//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenimKutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKUTUPHANEEntities1 : DbContext
    {
        public DBKUTUPHANEEntities1()
            : base("name=DBKUTUPHANEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TabloCezalar> TabloCezalar { get; set; }
        public virtual DbSet<TabloHareket> TabloHareket { get; set; }
        public virtual DbSet<TabloKasa> TabloKasa { get; set; }
        public virtual DbSet<TabloKategori> TabloKategori { get; set; }
        public virtual DbSet<TabloKitap> TabloKitap { get; set; }
        public virtual DbSet<TabloPersonel> TabloPersonel { get; set; }
        public virtual DbSet<TabloUyeler> TabloUyeler { get; set; }
        public virtual DbSet<TabloYazar> TabloYazar { get; set; }
        public virtual DbSet<TabloHakkımızda> TabloHakkımızda { get; set; }
        public virtual DbSet<Tabloİletisim> Tabloİletisim { get; set; }
        public virtual DbSet<TabloMesajlar> TabloMesajlar { get; set; }
        public virtual DbSet<TabloDuyuru> TabloDuyuru { get; set; }
    }
}
