//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenimKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabloHareket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabloHareket()
        {
            this.TabloCezalar = new HashSet<TabloCezalar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Kitap { get; set; }
        public Nullable<int> Uye { get; set; }
        public Nullable<int> Personel { get; set; }
        public Nullable<System.DateTime> AlisTarihi { get; set; }
        public Nullable<System.DateTime> IadeTarih { get; set; }
        public Nullable<bool> IslemDurum { get; set; }
        public Nullable<System.DateTime> GetirdigiTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabloCezalar> TabloCezalar { get; set; }
        public virtual TabloKitap TabloKitap { get; set; }
        public virtual TabloUyeler TabloUyeler { get; set; }
        public virtual TabloPersonel TabloPersonel { get; set; }
    }
}
